spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  batch:
    jdbc:
      initialize-schema: always
